"""username fixed

Revision ID: 2874c4d5434f
Revises: 3718052fdef8
Create Date: 2022-10-06 20:13:33.212806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2874c4d5434f'
down_revision = '3718052fdef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='users')
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
