"""added username

Revision ID: 3718052fdef8
Revises: a8515b674fca
Create Date: 2022-10-06 19:56:18.440949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3718052fdef8'
down_revision = 'a8515b674fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
